## Imports

### Librairies

In [43]:
import numpy as np
import pandas as pd
import random
import warnings

warnings.filterwarnings("ignore")
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 60)

import matplotlib.pyplot as plt
import sys 

from datetime import datetime, date, timedelta

import lightgbm as lgb

from sklearn.metrics import r2_score
from scipy.stats import pearsonr

### Data

In [19]:
train = pd.read_csv("D:/GitHub/Dataset/g-research-crypto-forecasting/train.csv")

### Data transformation

In [20]:
# We change timestamp data to date (in seconde frequence)
first_step = 0
step = 1000000
df = pd.DataFrame()

for rows_interval in range(first_step, train.shape[0], step):
    tmp_df = train.iloc[rows_interval:rows_interval + step]
    tmp_df['datetime'] = tmp_df.timestamp.apply(datetime.fromtimestamp)
    df = pd.concat([df, tmp_df], axis=0)

### Train/Test & Validation Split

In [21]:
# Creating a train_test & validation set 
split_date = '2021-06-18'
train_test_set = df.loc[df.datetime <= split_date].copy()
validation_set = df.loc[df.datetime > split_date].copy()

### Data Transformation

In [22]:
#We replace eacch Target's null valu to its median
train_test_set['Target'] = train_test_set['Target'].fillna(train_test_set['Target'].median())

### Feature creation

In [33]:
# Here we are splitting our dataset by Asset
l_train_test_set = []

for asset in range(0,14):
    l_train_test_set.append(train_test_set[train_test_set.Asset_ID == asset])

In [41]:
# Here we are going to create, for each asset, 15 shifted columns from our Target 
for i in  range(len(l_train_test_set)):
    l_train_test_set[i]['Target_lag1'] = l_train_test_set[i]['Target'].shift(1)
    l_train_test_set[i]['Target_lag2'] = l_train_test_set[i]['Target'].shift(2)
    l_train_test_set[i]['Target_lag3'] = l_train_test_set[i]['Target'].shift(3)
    l_train_test_set[i]['Target_lag4'] = l_train_test_set[i]['Target'].shift(4)
    l_train_test_set[i]['Target_lag5'] = l_train_test_set[i]['Target'].shift(5)
    l_train_test_set[i]['Target_lag6'] = l_train_test_set[i]['Target'].shift(6)
    l_train_test_set[i]['Target_lag7'] = l_train_test_set[i]['Target'].shift(7)
    l_train_test_set[i]['Target_lag8'] = l_train_test_set[i]['Target'].shift(8)
    l_train_test_set[i]['Target_lag9'] = l_train_test_set[i]['Target'].shift(9)
    l_train_test_set[i]['Target_lag10'] = l_train_test_set[i]['Target'].shift(10)
    l_train_test_set[i]['Target_lag11'] = l_train_test_set[i]['Target'].shift(11)
    l_train_test_set[i]['Target_lag12'] = l_train_test_set[i]['Target'].shift(12)
    l_train_test_set[i]['Target_lag13'] = l_train_test_set[i]['Target'].shift(13)
    l_train_test_set[i]['Target_lag14'] = l_train_test_set[i]['Target'].shift(14)
    l_train_test_set[i]['Target_lag15'] = l_train_test_set[i]['Target'].shift(15)

In [42]:
l_train_test_set[0]

,timestamp,Asset_ID,Count,Open,High,Low,Close,Volume,VWAP,Target,datetime,Target_lag1,Target_lag2,Target_lag3,Target_lag4,Target_lag5,Target_lag6,Target_lag7,Target_lag8,Target_lag9,Target_lag10,Target_lag11,Target_lag12,Target_lag13,Target_lag14,Target_lag15
1,1514764860,0,5.0,8.5300,8.5300,8.5300,8.5300,78.380000,8.530000,-0.014399,2018-01-01 01:01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1514764920,0,7.0,8.5300,8.5300,8.5145,8.5145,71.390000,8.520215,-0.015875,2018-01-01 01:02:00,-0.014399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1514764980,0,45.0,8.5065,8.5299,8.4848,8.4848,1546.820000,8.501394,-0.015410,2018-01-01 01:03:00,-0.015875,-0.014399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1514765040,0,14.0,8.5009,8.5066,8.4744,8.5009,125.800000,8.479810,-0.012524,2018-01-01 01:04:00,-0.015410,-0.015875,-0.014399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,1514765100,0,5.0,8.5007,8.5007,8.4560,8.4560,125.010000,8.458435,-0.005940,2018-01-01 01:05:00,-0.012524,-0.015410,-0.015875,-0.014399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22320725,1623966960,0,280.0,349.5105,349.5400,349.2500,349.4320,550.768335,349.423410,0.000700,2021-06-17 23:56:00,0.000885,0.000848,0.000278,0.001175,-0.000362,0.000162,-0.000425,-0.000426,-0.001273,-0.001565,-0.000061,-0.000656,-0.000305,-0.000390,-0.000731
22320739,1623967020,0,256.0,349.4335,349.5370,349.2000,349.3180,522.682200,349.386388,0.000147,2021-06-17 23:57:00,0.000700,0.000885,0.000848,0.000278,0.001175,-0.000362,0.000162,-0.000425,-0.000426,-0.001273,-0.001565,-0.000061,-0.000656,-0.000305,-0.000390
22320753,1623967080,0,137.0,349.3350,349.6460,349.2600,349.4485,159.480300,349.474824,0.001302,2021-06-17 23:58:00,0.000147,0.000700,0.000885,0.000848,0.000278,0.001175,-0.000362,0.000162,-0.000425,-0.000426,-0.001273,-0.001565,-0.000061,-0.000656,-0.000305
22320767,1623967140,0,190.0,349.4485,349.5270,349.1300,349.4445,436.659756,349.381573,0.002417,2021-06-17 23:59:00,0.001302,0.000147,0.000700,0.000885,0.000848,0.000278,0.001175,-0.000362,0.000162,-0.000425,-0.000426,-0.001273,-0.001565,-0.000061,-0.000656
22320781,1623967200,0,296.0,349.2925,349.4000,349.1200,349.1605,418.395200,349.240285,0.001778,2021-06-18 00:00:00,0.002417,0.001302,0.000147,0.000700,0.000885,0.000848,0.000278,0.001175,-0.000362,0.000162,-0.000425,-0.000426,-0.001273,-0.001565,-0.000061

## LightGBM Model (test)

In [49]:
X = l_train_test_set[0].drop(columns = ['Target','datetime'])
y = l_train_test_set[0]['Target']

In [50]:
# split the dataset into the training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [51]:
clf = lgb.LGBMRegressor()
clf.fit(X_train, y_train)

LGBMRegressor()

In [52]:
y_pred= clf.predict(X_test)

In [60]:
print(' R2: {0:0.4f}'. format(r2_score(y_pred, y_test)))

 R2: 0.7584

In [73]:
pearsonr(y_pred, y_test)

(0.89780803878799, 0.0)